spring.application.name=auth-backend-api
server.port=9090

# Carga el archivo .env local (no se sube a git)
spring.config.import=optional:file:./.env[.properties]

# --------------- DataSource (Postgres - Neon) --------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------- JPA / Hibernate --------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
