spring.application.name=auth-backend-api
server.port=9090

# --------------- DataSource (Postgres) --------------------------------------
spring.datasource.url=jdbc:postgresql://ep-still-queen-ajagiola-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iSnV9tXrauY7
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------- JWT --------------------------------------------------------
# Secret must be at least 32 chars (256 bits) for HS256
jwt.secret=${JWT_SECRET:change-this-super-secret-key-for-jwt-signing-256-bits-min}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# --------------- JPA / Hibernate --------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
